services:
  devcontainer:
    image: ghcr.io/liquescent-development/devcontainer:latest
    
    # Environment variables from .env file are automatically loaded
    environment:
      # Timezone
      - TZ=${TZ:-UTC}
      
      # 1Password Configuration - only pass if set
      - OP_SERVICE_ACCOUNT_TOKEN=${OP_SERVICE_ACCOUNT_TOKEN:-}
      - OP_CONNECT_HOST=${OP_CONNECT_HOST:-}
      - OP_CONNECT_TOKEN=${OP_CONNECT_TOKEN:-}
      
      # Custom allowed domains for firewall
      - CUSTOM_ALLOWED_DOMAINS=${CUSTOM_ALLOWED_DOMAINS:-}
      
      # SOCKS5 proxy configuration
      - SOCKS5_ENABLED=${SOCKS5_ENABLED:-true}
      - SOCKS5_HOST=${SOCKS5_HOST:-host.docker.internal}
      - SOCKS5_PORT=${SOCKS5_PORT:-1080}
      
      # Git configuration mounting
      - MOUNT_HOST_GIT_CONFIG=${MOUNT_HOST_GIT_CONFIG:-false}
      
      # Container environment
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - SSH_AUTH_SOCK=/ssh-agent
      - DEVCONTAINER=true
    
    volumes:
      # Workspace
      - ..:/workspace:cached
      
      # Claude configuration
      - ${HOME}/.claude/agents:/home/node/.claude/agents:ro
      - ${HOME}/.claude/CLAUDE.md:/home/node/.claude/CLAUDE.md:ro
      - ${HOME}/.claude/settings.json:/home/node/.claude/settings.json:ro
      
      # Git configuration and SSH
      - ${HOME}/.gitconfig:/home/node/.gitconfig.host:ro
      - ${HOME}/.ssh:/home/node/.ssh-host:ro
      
      # SSH agent forwarding
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
      
      # Command history persistence
      - devcontainer-history:/commandhistory
      
      # Fonts (macOS specific path, will be ignored on other systems)
      - ${HOME}/Library/Fonts:/usr/share/fonts/truetype/custom:ro
    
    # Network capabilities for firewall
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    # Add host.docker.internal for accessing host services
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    # Keep container running
    command: sleep infinity
    
    # Set working directory
    working_dir: /workspace
    
    # Run as node user
    user: node

volumes:
  devcontainer-history: